---
- hosts: all
  become: yes
  vars:
    postgresql_version: 9.5
    ansible_os_family:  'Debian'
    rvm1_rubies:
      - 'ruby-2.3.0'
  roles:
    - ANXS.postgresql
    - rvm_io.rvm1-ruby
  tasks:
    - apt: name={{item}} state=present update_cache=yes
      with_items:
        - vim
